name: CI

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          # Build your HTML page (if needed)
          # Deploy to GitHub Pages
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          npm install -g gh-pages
          npm run build  # or any other build step
          npx gh-pages -d build