name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Add any necessary build or test commands here
          # For a simple HTML page, this may be empty or just copying files

      # Add additional steps if needed, such as deploying to a web server